name: flutter_application_1
description: "RoomMate Finder - App de búsqueda de roommates y vivienda"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  
  # Backend
  supabase_flutter: ^2.5.0
  http: ^1.1.0
  
  # Mapas
  flutter_map: ^7.0.0
  latlong2: ^0.9.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  
  # Imágenes
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  
  # UI Mejorada
  flutter_svg: ^2.0.10
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  
  # Utils
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  
  # Estado
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true